# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rnn_brute_force <- function(data, k, metric = "euclidean", n_threads = 0L, block_size = 64L, grain_size = 1L, verbose = FALSE) {
    .Call(`_rnndescent_rnn_brute_force`, data, k, metric, n_threads, block_size, grain_size, verbose)
}

rnn_brute_force_query <- function(reference, query, k, metric = "euclidean", block_size = 64L, n_threads = 0L, grain_size = 1L, verbose = FALSE) {
    .Call(`_rnndescent_rnn_brute_force_query`, reference, query, k, metric, block_size, n_threads, grain_size, verbose)
}

reverse_nbr_size_impl <- function(nn_idx, k, len, include_self = FALSE) {
    .Call(`_rnndescent_reverse_nbr_size_impl`, nn_idx, k, len, include_self)
}

rnn_idx_to_graph_self <- function(data, idx, metric = "euclidean", n_threads = 0L, grain_size = 1L, verbose = FALSE) {
    .Call(`_rnndescent_rnn_idx_to_graph_self`, data, idx, metric, n_threads, grain_size, verbose)
}

rnn_idx_to_graph_query <- function(reference, query, idx, metric = "euclidean", n_threads = 0L, grain_size = 1L, verbose = FALSE) {
    .Call(`_rnndescent_rnn_idx_to_graph_query`, reference, query, idx, metric, n_threads, grain_size, verbose)
}

merge_nn <- function(nn_idx1, nn_dist1, nn_idx2, nn_dist2, is_query, block_size, n_threads, grain_size = 1L, verbose = FALSE) {
    .Call(`_rnndescent_merge_nn`, nn_idx1, nn_dist1, nn_idx2, nn_dist2, is_query, block_size, n_threads, grain_size, verbose)
}

merge_nn_all <- function(nn_graphs, is_query, block_size, n_threads, grain_size = 1L, verbose = FALSE) {
    .Call(`_rnndescent_merge_nn_all`, nn_graphs, is_query, block_size, n_threads, grain_size, verbose)
}

nn_descent <- function(data, nn_idx, nn_dist, metric = "euclidean", max_candidates = 50L, n_iters = 10L, delta = 0.001, low_memory = TRUE, block_size = 16384L, n_threads = 0L, grain_size = 1L, verbose = FALSE, progress = "bar") {
    .Call(`_rnndescent_nn_descent`, data, nn_idx, nn_dist, metric, max_candidates, n_iters, delta, low_memory, block_size, n_threads, grain_size, verbose, progress)
}

diversify_sp_cpp <- function(data, graph_list, metric = "euclidean", prune_probability = 1.0) {
    .Call(`_rnndescent_diversify_sp_cpp`, data, graph_list, metric, prune_probability)
}

diversify_always_sp_cpp <- function(data, graph_list, metric = "euclidean") {
    .Call(`_rnndescent_diversify_always_sp_cpp`, data, graph_list, metric)
}

merge_graph_lists_cpp <- function(gl1, gl2) {
    .Call(`_rnndescent_merge_graph_lists_cpp`, gl1, gl2)
}

degree_prune_cpp <- function(graph_list, max_degree, n_threads = 0L, grain_size = 1L) {
    .Call(`_rnndescent_degree_prune_cpp`, graph_list, max_degree, n_threads, grain_size)
}

random_knn_cpp <- function(data, k, metric = "euclidean", order_by_distance = TRUE, block_size = 4096L, n_threads = 0L, grain_size = 1L, verbose = FALSE) {
    .Call(`_rnndescent_random_knn_cpp`, data, k, metric, order_by_distance, block_size, n_threads, grain_size, verbose)
}

random_knn_query_cpp <- function(reference, query, k, metric = "euclidean", order_by_distance = TRUE, block_size = 4096L, n_threads = 0L, grain_size = 1L, verbose = FALSE) {
    .Call(`_rnndescent_random_knn_query_cpp`, reference, query, k, metric, order_by_distance, block_size, n_threads, grain_size, verbose)
}

nn_query <- function(reference, reference_graph_list, query, nn_idx, nn_dist, metric = "euclidean", epsilon = 0.1, n_threads = 0L, grain_size = 1L, verbose = FALSE) {
    .Call(`_rnndescent_nn_query`, reference, reference_graph_list, query, nn_idx, nn_dist, metric, epsilon, n_threads, grain_size, verbose)
}

