# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rnn_brute_force <- function(data, k, metric = "euclidean", n_threads = 0L, block_size = 64L, grain_size = 1L, verbose = FALSE) {
    .Call(`_rnndescent_rnn_brute_force`, data, k, metric, n_threads, block_size, grain_size, verbose)
}

rnn_brute_force_query <- function(reference, query, k, metric = "euclidean", n_threads = 0L, block_size = 64L, grain_size = 1L, verbose = FALSE) {
    .Call(`_rnndescent_rnn_brute_force_query`, reference, query, k, metric, n_threads, block_size, grain_size, verbose)
}

reverse_nbr_size_impl <- function(nn_idx, k, len, include_self = FALSE) {
    .Call(`_rnndescent_reverse_nbr_size_impl`, nn_idx, k, len, include_self)
}

rnn_idx_to_graph <- function(data, idx, metric = "euclidean", verbose = FALSE) {
    .Call(`_rnndescent_rnn_idx_to_graph`, data, idx, metric, verbose)
}

merge_nn <- function(nn_idx1, nn_dist1, nn_idx2, nn_dist2, is_query, n_threads, block_size, grain_size = 1L, verbose = FALSE) {
    .Call(`_rnndescent_merge_nn`, nn_idx1, nn_dist1, nn_idx2, nn_dist2, is_query, n_threads, block_size, grain_size, verbose)
}

merge_nn_all <- function(nn_graphs, is_query, n_threads, block_size, grain_size = 1L, verbose = FALSE) {
    .Call(`_rnndescent_merge_nn_all`, nn_graphs, is_query, n_threads, block_size, grain_size, verbose)
}

nn_descent <- function(data, nn_idx, nn_dist, metric = "euclidean", max_candidates = 50L, n_iters = 10L, delta = 0.001, low_memory = TRUE, n_threads = 0L, block_size = 16384L, grain_size = 1L, verbose = FALSE, progress = "bar") {
    .Call(`_rnndescent_nn_descent`, data, nn_idx, nn_dist, metric, max_candidates, n_iters, delta, low_memory, n_threads, block_size, grain_size, verbose, progress)
}

nn_descent_query <- function(reference, reference_idx, reference_dist, query, nn_idx, nn_dist, metric = "euclidean", max_candidates = 50L, n_iters = 10L, delta = 0.001, low_memory = TRUE, n_threads = 0L, block_size = 16384L, grain_size = 1L, verbose = FALSE, progress = "bar") {
    .Call(`_rnndescent_nn_descent_query`, reference, reference_idx, reference_dist, query, nn_idx, nn_dist, metric, max_candidates, n_iters, delta, low_memory, n_threads, block_size, grain_size, verbose, progress)
}

random_knn_cpp <- function(data, k, metric = "euclidean", order_by_distance = TRUE, n_threads = 0L, block_size = 4096L, grain_size = 1L, verbose = FALSE) {
    .Call(`_rnndescent_random_knn_cpp`, data, k, metric, order_by_distance, n_threads, block_size, grain_size, verbose)
}

random_knn_query_cpp <- function(reference, query, k, metric = "euclidean", order_by_distance = TRUE, n_threads = 0L, block_size = 4096L, grain_size = 1L, verbose = FALSE) {
    .Call(`_rnndescent_random_knn_query_cpp`, reference, query, k, metric, order_by_distance, n_threads, block_size, grain_size, verbose)
}

