# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

nn_descent <- function(data, idx, dist, metric = "euclidean", max_candidates = 50L, n_iters = 10L, delta = 0.001, rho = 0.5, use_set = FALSE, fast_rand = FALSE, parallelize = FALSE, grain_size = 1L, verbose = FALSE) {
    .Call(`_rnndescent_nn_descent`, data, idx, dist, metric, max_candidates, n_iters, delta, rho, use_set, fast_rand, parallelize, grain_size, verbose)
}

rnn_brute_force <- function(data, k, metric = "euclidean", parallelize = FALSE, grain_size = 1L, verbose = FALSE) {
    .Call(`_rnndescent_rnn_brute_force`, data, k, metric, parallelize, grain_size, verbose)
}

random_nbrs_cpp <- function(data, k, metric = "euclidean", parallelize = FALSE, grain_size = 1L) {
    .Call(`_rnndescent_random_nbrs_cpp`, data, k, metric, parallelize, grain_size)
}

